config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get "privacy" => 'documents#privacy', as: :privacy
  get "terms" => 'documents#terms', as: :terms

  get '/auth/:provider/callback', to: 'providers#create'

  resources :providers, :feeds

  namespace :twitter do
    resources :feeds
    resources :searches
    resources :timelines
  end

  namespace :instagram do
    resources :users
    resources :tags
  end

  namespace :facebook do
    resources :pages
    resource :photos
    resources :user_feeds
  end

end

app/models/provider.rb
class Provider < ActiveRecord::Base

  scope :instagram, -> { where(name: "instagram") }
  scope :facebook,  -> { where(name: "facebook") }
  scope :twitter,   -> { where(name: "twitter") }
  scope :for_user,  -> (user) { where(user: user) }

  belongs_to :user
  has_many   :feeds, dependent: :destroy

  after_create :build_feed

  def build_feed
    if name.inquiry.instagram?
      Instagram::User.create(user: user, handle: nickname)
    end
  end

  class << self
    def instagram_for_user(user)
      instagram.find_by(user: user)
    end
    def facebook_for_user(user)
      facebook.find_by(user: user)
    end
    def twitter_for_user(user)
      twitter.find_by(user: user)
    end
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  skip_before_filter :signed_in?, only: [:create]

  def create
    if env["omniauth.params"]["to"] == 'signin'
      user = NewUserManager.new(request.env["omniauth.auth"]).create
      session[:user_id] = user.id
    else
      ProviderStore.create(current_user, request.env["omniauth.auth"])
    end
    redirect_to root_path
  end

  def destroy
    provider = current_user.providers.find(params[:id])
    provider.destroy if provider

    redirect_to root_path
  end
end

app/views/providers/_connect.html.haml
.feed-section
  %p
    Please connect to #{provider}

app/views/providers/_facebook.html.haml
%p
  Facebook

  = link_to 'disconnect', provider_path(provider.name), method: :delete
  \-
  = link_to 'new page feed', new_facebook_page_path
  \-
  = link_to 'your photos feed', new_facebook_photos_path

app/views/providers/_instagram.html.haml
%p
  = provider.name
  = link_to 'disconnect', provider_path(provider.name), method: :delete
  \-
  = link_to 'new user feed', new_instagram_user_path
  \-
  = link_to 'new tag feed', new_instagram_tag_path

app/views/providers/_twitter.html.haml
%p
  = provider.name
  = link_to 'disconnect', provider_path(provider.name), method: :delete
  \-
  = link_to 'new user timeline feed', new_twitter_timeline_path
  \-
  = link_to 'new search feed', new_twitter_search_path

app/views/providers/index.html.haml
%h2 Providers

%h3 Available Services

- unless current_user.has_provider?('twitter')
  %p
    = link_to 'Twitter', '/auth/twitter'

- unless current_user.has_provider?('instagram')
  %p
    = link_to 'Instagram', '/auth/instagram'

- unless current_user.has_provider?('facebook')
  %p
    = link_to 'Facebook', '/auth/facebook'

%h3 Creata a Feed
  = link_to "Instagram", new_feed_path(provider: 'instagram')

%h3 Your Connected Services

- current_user.providers.each do |provider|
  %p
    = provider.name
    = link_to 'disconnect', provider_path(provider.name), method: :delete