config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get "privacy" => 'documents#privacy', as: :privacy
  get "terms" => 'documents#terms', as: :terms

  get '/auth/:provider/callback', to: 'providers#create'

  resources :providers, :feeds

  namespace :twitter do
    resources :feeds
    resources :searches
    resources :timelines
  end

  namespace :instagram do
    resources :users
    resources :tags
  end

  namespace :facebook do
    resources :pages
    resource :photos
    resources :user_feeds
  end

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
  belongs_to :provider

  TOTAL_FEEDS_ALLOWED = 10
end

app/models/instagram/feed.rb
#class Instagram::Feed < Feed
  #after_create :post_process

  #def post_process
    #FeedManagement::Instagram::User.new(self)
  #end
#end

app/controllers/feeds/instagram/recent_media_controller.rb
module Feeds
  module Instagram
    class RecentMediaController < ApplicationController
      def create
        id = FeedManagement::Instagram.get_id_from_handle(provider.token, handle)
        render text: id
      end

      private

      def provider
        @provider ||= Provider.instagram_for_user(current_user)
      end

      def handle
        params[:handle]
      end
    end
  end
end

app/controllers/feeds/instagram_feeds_controller.rb
class Feeds::InstagramFeedsController < ApplicationController
  def create
    get_provider
    make_new_feed

    if @feed.save
      render json: @feed
    end
  end

  private

  def get_instagram_user_id
    FeedManagement::Instagram.get_id_from_handle(@provider.token, safe_params[:handle])
  end

  def make_new_feed
    id = get_instagram_user_id
    @feed = Feed.new(user: current_user, provider: @provider, meta: {user_id: id})
  end

  def get_provider
    @provider = Provider.instagram_for_user(current_user)
  end

  def find_feed
    @feed = current_user.feeds.find params[:id]
  end

  def safe_params
    params.require(:feed).permit(:query, :handle)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :create_feed, only: [:create]

  def show
    find_feed

    @feed = current_user.feeds.find params[:id]
  end

  def index
    @feeds = current_user.feeds
  end

  def destroy
    find_feed

    @feed.destroy
    puts 'Destroy feed'

    respond_to do |format|
      format.json { render(json: @feed, status: 200) }
    end
  end

  def create
    if @feed.errors.empty?
      success_as_json
    else
      errors_as_json
    end
  end

  private

  def find_feed
    @feed = current_user.feeds.find params[:id]
  end

  def response_to_json
    respond_to do |format|
      format.json do
        type = self.class.to_s.deconstantize.downcase
        render(json: { data: render_to_string(partial: '/feeds/table', locals: {type: type}, formats: [:html]) }, status: 200)
      end
    end
  end
  alias_method :success_as_json, :response_to_json

  def errors_as_json
    respond_to do |format|
      format.json do
        render(json: { errors: @feed.errors.values, status: :errors })
      end
    end
  end

  def create_feed
  end
end

app/views/feeds/_instagram.html.haml
- feeds = current_user.feeds_for(type)

%table.pure-table.pure-table-horizontal.max.feeds-table
  %tbody
    %tr
      - if feeds.empty?
        %td{colspan: 3, class: 'no-feeds-message'}
          %p
            You don't have a feed

      - else
        - feeds.each do |feed|
          - feed = "Presenters::Feeds::#{type.classify}".constantize.new(feed)
          %tr
            %td
              = feed.query
              -#Word Search: Lots of text to test test test testing green eggs and ham

            %td
              %span{title: feed.fetched_at}
                = "#{time_ago_in_words(feed.fetched_at)} ago" if feed.fetched_at
                = "waiting..." unless feed.fetched_at

            %td.right-align
              %a{ class: "btn-floating tooltipped", href: url_for_api(feed.id), target: '_blank', data: { position: "top", tooltip: "Open" } }
                %i.material-icons.small launch

app/views/feeds/_table.html.haml
- feeds = current_user.feeds_for(type)

%table.pure-table.pure-table-horizontal.max.feeds-table
  - unless feeds.empty?
    %thead
      %tr
        %th{ colspan: 4 } Your #{type.capitalize} Feeds
  %tbody
    %tr
      - if feeds.empty?
        %td{colspan: 4, class: 'no-feeds-message'}
          %p
            You don't have any #{type} feeds.

      - else
        - feeds.each do |feed|
          - feed = "Presenters::Feeds::#{type.classify}".constantize.new(feed)
          %tr
            %td
              = feed.query
              -#Word Search: Lots of text to test test test testing green eggs and ham

            %td
              %span{title: feed.fetched_at}
                = "#{time_ago_in_words(feed.fetched_at)} ago" if feed.fetched_at
                = "waiting..." unless feed.fetched_at

            %td.right-align
              %a{ class: "btn-floating tooltipped", href: url_for_api(feed.id), target: '_blank', data: { position: "top", tooltip: "Open" } }
                %i.material-icons.small launch

            %td.right-align
              = link_to feed_path(feed.feed), method: :delete, remote: true, data: { confirm: 'Are you sure you want to delete this feed forever?', position: "top", tooltip: "Delete!" }, class: 'warning tooltipped delete-feed' do
                %i.material-icons.small delete_forever

app/views/feeds/index.html.haml
= render partial: 'feeds/table', locals: {feeds: @feeds}

app/views/feeds/new.html.haml
= form_for Feed.new do |form|
  = text_field :handle
  = form.submit class: 'btn'

app/views/feeds/show.html.haml
.side-menu
  %ul
    - current_user.feeds.each do |feed|
      %li= link_to feed.provider.name, feed

.main-content
  %h3 Last Fetched
  .last-fetched.box.box-light
    %p
      - if @feed.fetched_at
        Last fetched on #{time_ago_in_words(@feed.fetched_at)}
      - else
        Feed hasn't been fetched yet


  %h3 API Endpoint
  .api-endpoint.box.box-light
    %code
      %pre
        http://api.bitsalad.co/v1/feeds/#{@feed.id}